//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.05 at 05:50:11 PM EEST 
//


package org.datacontract.schemas._2004._07.coffeebreakservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.datacontract.schemas._2004._07.coffeebreakservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CoffeeBreakRequest_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoffeeBreakService", "CoffeeBreakRequest");
    private final static QName _CoffeeBreakResponse_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoffeeBreakService", "CoffeeBreakResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datacontract.schemas._2004._07.coffeebreakservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoffeeBreakResponse }
     * 
     */
    public CoffeeBreakResponse createCoffeeBreakResponse() {
        return new CoffeeBreakResponse();
    }

    /**
     * Create an instance of {@link CoffeeBreakRequest }
     * 
     */
    public CoffeeBreakRequest createCoffeeBreakRequest() {
        return new CoffeeBreakRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoffeeBreakRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoffeeBreakService", name = "CoffeeBreakRequest")
    public JAXBElement<CoffeeBreakRequest> createCoffeeBreakRequest(CoffeeBreakRequest value) {
        return new JAXBElement<CoffeeBreakRequest>(_CoffeeBreakRequest_QNAME, CoffeeBreakRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoffeeBreakResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoffeeBreakService", name = "CoffeeBreakResponse")
    public JAXBElement<CoffeeBreakResponse> createCoffeeBreakResponse(CoffeeBreakResponse value) {
        return new JAXBElement<CoffeeBreakResponse>(_CoffeeBreakResponse_QNAME, CoffeeBreakResponse.class, null, value);
    }

}
